name: Go test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set version
      run: V=${{ github.ref_name }} && VT="${V#v}" && sed "s@APP_VERSION@$VT@" misc/version.go.in > misc/version.go

    - name: Build
      run: CGO_ENABLED=0 go build -v

    - name: Test
      run: go test -v ./...

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set app version
      run: V=${{ github.ref_name }} && VT="${V#v}" && sed "s@APP_VERSION@$VT@" misc/version.go.in > misc/version.go

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build binary image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .docker/Dockerfile-bin
        tags: nxs-backup:local
